# Generated by Django 3.0.5 on 2021-03-30 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='username',
            new_name='name',
        ),
    ]
