# Generated by Django 3.0.5 on 2021-03-31 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210331_0141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_data',
        ),
    ]
